server:
  port: 8080
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
#mysql

#mybatis:
  #type-aliases-package: com.qhit.demo.pojo
  mybatis.config-location=classpath: /mybatis-config.xml

#
#视图层控制
  spring.mvc.view.prefix: classpath:/templates/
  spring.mvc.view.suffix: .html
  spring.mvc.static-path-pattern: /static/**

